//If you install vscode rest client extension. You can sent http requests here
// Saves having to use the browser or tools like postman

get http://localhost:5000/fake

###
get http://localhost:5000/api/meta/events

###
get http://localhost:5000/testerror

###
get http://localhost:5000

###
get http://localhost:5000/api/predict/1995-01-21
